baseurl = "https://interetro.rbind.io/"
publishDir = "public"
title = "interetro"
author = "Qiu Rui"
canonifyurls = true
languagecode = "en"
paginate = 3
theme = "hugo-renga"

enableEmoji = true
hasCJKLanguage = true

disqusShortname = "rexarski"
googleAnalytics = "UA-80926729-1"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
pagetitle = "interesting retrospectives"
copyright = "Â© 2020 All rights reserved."
copyrightUrl = "https://interetro.rbind.io"
faviconfile = "image/favicon.png"
logofile = "image/rexarski.jpg"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "rexarski"
# linkedin = ""
twitter = "rexarski"
# medium = "rexarski"
# vsco = ""
# instagram = "rexarski"
# telegram = "ghgibus"
# unsplash = ""
email = "qiurui416@gmail.com"

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 1

[[menu.primary]]
identifier = "project"
name = "Project"
url = "/project/"
weight = 2

[[menu.primary]]
identifier = "uses"
name = "Uses"
url = "/uses/"
weight = 3

[[menu.primary]]
identifier = "photos"
name = "ðŸ¥‘"
url = "https://airavo.netlify.app"
weight = 4

[[menu.primary]]
identifier = "telegram"
name = "Telegram Channel"
url = "https://t.me/itsnopie"
weight = 5

[[menu.primary]]
identifier = "ä¸­æ–‡"
name = "ä¸­æ–‡"
url = "/cn/"
weight = 76